# Generated by Django 4.0 on 2025-01-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
            ],
        ),
    ]
