# Generated by Django 4.2 on 2025-01-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('category', models.CharField(choices=[('Python', 'Pythonの勉強'), ('Django', 'Djangoの勉強'), ('HTML/CSS', 'HTML/CSSの勉強'), ('JavaScript', 'JavaScriptの勉強'), ('その他', 'その他の勉強')], max_length=50, verbose_name='カテゴリ')),
            ],
        ),
    ]
